# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-25 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_cartinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('aname', models.CharField(max_length=20, verbose_name='收货人姓名')),
                ('aphone', models.CharField(max_length=20, verbose_name='收货人电话')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Users')),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNo', models.CharField(max_length=50, verbose_name='订单号')),
                ('cals', models.TextField(verbose_name='订单商品描述')),
                ('orderStatus', models.IntegerField(choices=[(1, '未支付'), (2, '已支付'), (3, '已取消'), (4, '已完成')], default=1, verbose_name='订单状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Users')),
            ],
        ),
        migrations.AlterModelOptions(
            name='cartinfo',
            options={'verbose_name': '购物车', 'verbose_name_plural': '购物车'},
        ),
    ]
